[program:horizon]
process_name=%(program_name)s
command=php /var/www/clean2go/fixit_laravel/artisan horizon
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/clean2go/fixit_laravel/storage/logs/horizon.log
stopwaitsecs=3600
